config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :conferences do
    resources :topics do
      member do
        put :vote
      end
    end
  end
  root 'conferences#index'
  get 'conferences/:conference_id/results' => 'topics#results'
  get 'topics/new' => 'topics#new'
  resources :schedules
  resources :schedule_slots

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :schedules
  has_many :topics
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  has_many :schedule_slots
  belongs_to :conference
end

app/models/schedule_slot.rb
class ScheduleSlot < ActiveRecord::Base
  belongs_to :schedule
  has_one :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :conference
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  # http_basic_authenticate_with name: 'admin@example.com', password: 'password'
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController

  def index
    @conferences = Conference.all
  end

  def show
    render json: Conference.find(params[:id]).to_json
  end

  private

  def permitted_params
    params.require(:conference).permit(:name, :start_date, :end_date, :description, :location)
  end
end

app/controllers/schedule_slots_controller.rb
class ScheduleSlotsController < ApplicationController

  def new
  end

  def create
    schedule_slot = ScheduleSlot.create(permitted_params)

    if schedule_slot.save
      head :created
    else
      head :unprocessable_entity
    end
  end

  private
  def permitted_params
    params.require(:schedule_slot).permit(:schedule_id, :start_time, :end_time)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def new
  end

  def create
    schedule = Schedule.create(permitted_params)

    if schedule.save
      head :created
    else
      head :unprocessable_entity
    end
  end

  private
  def permitted_params
    params.require(:schedule).permit(:conference_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    session[:votes] = 3 if session[:votes].nil?
    @votes = session[:votes]
    session[:topics] = {} if session[:topics].nil?
    @voted = session[:topics]
    @topics = Topic.where(conference_id: params[:conference_id])
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @topics.to_json }
    end
  end

  def show
    render json: Topic.find(params[:id]).to_json
  end

  def results
    @topics = Topic.where(conference_id: params[:conference_id]).sort_by{|t| -t.points}
  end

  def new
  end

  def create
    topic = Topic.create(permitted_params)
    confirm_save topic
  end

  def vote    
    if(session[:votes]) > 0
      topic = Topic.find(params[:id])
      topic.update(points: (topic.points + 1))
      topic.save
      session[:votes] = session[:votes] - 1
      session[:topics] ||= {}
      session[:topics][params[:id]] = session[:topics][params[:id]].to_i + 1
    end
    redirect_to conference_topics_url(params[:conference_id])
  end

  private

  def confirm_save topic
    if topic.save
      head :created
    else
      head :unprocessable_entity
    end
  end

  def permitted_params
    params.require(:topic).permit(:name, :type, :description, :facilitator, :points, :conference_id, :schedule_slots_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/schedule_slots_helper.rb
module ScheduleSlotsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/conferences/index.html.erb
<div class="container" role="main">
  <div class="row" style="text-align: center">
    <div class="col-lg-12">
      <br><br>
      
      <h1 style="text-align: center; padding-top: 0px; margin-top: 0px"><i class='tick' style="font-size:175px">R</i>unconference</h1>
      <hr style="width: 80%"/>
      <br />
      <h2 style="text-align: center">Conferences</h2>
      <% @conferences.each do |conference| %>
        <div class="card" style="width: 85%; text-align: center">
          <div class="col-lg-12" style="padding-left: 30px">
            <br /><br />
            <h1><%= conference.name %></h1>
            <h3><%= conference.description %></h3>
            <h2><%= conference.location %></h2>
            <br /><br />
            <%= link_to "View Conference Topics", conference_topics_path(conference_id: conference.id), class: "btn btn-success", style: "padding: 20px 20px 20px 20px" %>
            <br /><br /><br />
          </div>
        </div>
        <br><br>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Runconference</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/topics/index.html.erb
<div class="container" role="main">
  <div class="row" style="text-align: center">
    <div class="col-lg-12">
      <br><br>
      <h1 style="text-align: center">Conference Events</h1>
      <h3 style="text-align: center">Votes Remaining: <%= @votes %></h3>
      <% @topics.each do |topic| %>
        <div class="card" style="width: 85%; text-align: center">
          <div class="col-lg-12" style="padding-left: 30px">
            <br /><br />
            <h3><strong>Name: </strong><%= topic.name %></h3>
            <p><strong>Description: </strong><%= topic.description %></p>
            <p><strong>Facilitator: </strong><%= topic.facilitator %></p>
            <p>
              <% for i in 1..@voted["#{topic.id}"].to_i do %>
                <i class='mdi-action-favorite mdi-material-red'></i>
              <% end %>
            </p>
            <%= link_to "Vote", vote_conference_topic_path(params[:conference_id], topic.id), method: :put, class: "btn btn-primary", id: "btn_#{topic.id}" %>
            <br /><br /><br />
          </div>
        </div>
        <br><br>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/results.html.erb
<div class="container" role="main">
  <div class="row" style="text-align: center">
    <div class="col-lg-12">
      <br><br>
      <h1 style="text-align: center">Conference Topic Results</h1>
      <h3 style="text-align: center">Votes Remaining: <%= @votes %></h3>
      <% @topics.each do |topic| %>
        <div class="card" style="width: 85%; text-align: center">
          <div class="col-lg-12" style="padding-left: 30px">
            <br /><br />
            <h3><strong>Name: </strong><%= topic.name %></h3>
            <p><strong>Description: </strong><%= topic.description %></p>
            <p><strong>Facilitator: </strong><%= topic.facilitator %></p>
            <h1><strong>Votes: </strong><%= topic.points %></h1>
            <br /><br /><br />
          </div>
        </div>
        <br><br>
      <% end %>
    </div>
  </div>
</div>